org.gradle.jvmargs=-Xmx4096M
android.useAndroidX=true
android.enableJetifier=false
org.gradle.java.home=C:/Program Files/Java/jdk-17/
android.overridePathCheck=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
